# Generated by Django 5.0 on 2024-01-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='voiture_images/')),
                ('marque', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('disponibilite', models.BooleanField(default=True)),
                ('categorie', models.CharField(max_length=50)),
                ('carburant', models.CharField(max_length=50)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date_de_creation'],
            },
        ),
    ]
