# Generated by Django 5.0 on 2024-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='categorie',
            field=models.CharField(choices=[('economy', 'Economy'), ('luxe', 'Luxe'), ('suv', 'SUV'), ('standard', 'Standard')], max_length=20),
        ),
    ]
