# Generated by Django 5.0 on 2024-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0002_alter_voiture_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='reduction_disponible',
            field=models.BooleanField(default=False),
        ),
    ]
