# Generated by Django 5.0 on 2024-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0003_voiture_reduction_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='disponibilite',
        ),
        migrations.AddField(
            model_name='voiture',
            name='Availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance'), ('rented', 'Rented')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='voiture',
            name='KM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiture',
            name='State',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20),
        ),
    ]
