# Generated by Django 5.0 on 2024-01-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0005_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
