# Generated by Django 5.0 on 2024-01-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationsApp', '0002_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='numero',
        ),
    ]
